### ISSUE TITLE
Forms and Form Labels - CSS

### ISSUE THREAD

**Issue by RowenScout** [nosrac77/hormone-tracker-app#21]
add forms in HTML for each key value pair in constructor function:
  - date, dosage, tLevel, eLevel, log

Research units used in lab results for testosterone and estrogen. Add those as labels to forms.

**Comment by RowenScout** [comment]
Carson added HTML. Needs styling.

**Comment by nosrac77** [comment]
They've been styled. I can work on researching lab measurement units and I can add them to the labels accordingly.

**Comment by nosrac77** [comment]
The media queries work as intended. I can keep this issue open until I do the research or one of you two can close it if you think the work I've done is sufficient (I'll push up a PR soon).
