### ISSUE TITLE
Create Logic for localStorage data - JavaScript

### ISSUE THREAD

**Issue by nosrac77** [nosrac77/hormone-tracker-app#5]

**Comment by RowenScout** [comment]
Does this work? 
`if (localstorage.dataPoints) { dataPoints = localstorage.dataPoints;

} else {
  localstorage.dataPoints = dataPoints;
}`

**Comment by RowenScout** [comment]
We're abandoning a global datapoints array in favor of using localstorage.dataPoints = [ ];
